### PR TITLE
Added code to install any missing packages

### PR DESCRIPTION
**Pull request by jmwerner**
Thanks for making this cookbook! I added some simple code to install any missing R packages in case anyone else gets that error while running the makefile. Feel free to take it or leave it. Cheers!

### CODE REVIEW

**Comment by mavam** [comment]
That's a useful addition, thanks. Would you mind reformatting the patch so that it is consistent with the coding style of the rest of the file? Just use the reformatted snippet below.

```R
needed_packages = c("ggplot2", "reshape2", "grid", "RColorBrewer")
if (length(setdiff(needed_packages, rownames(installed.packages()))) > 0) {
  install.packages(setdiff(needed_packages, rownames(installed.packages())),
                   dependencies=TRUE, repos="http://cran.r-project.org")
}
```

Once you push those nits to your branch I'll go ahead and merge.

**Comment by jmwerner** [comment]
I believe I made all of the required changes, please let me know if I missed something

**Comment by mavam** [comment]
Looks great! The final thing missing is squashing your commits into a single one.

One of doing that: `git rebase -i HEAD~2`

**Comment by jmwerner** [comment]
I've never used rebase before, that made for some nice reading. Let me know if something is still not quite right. Thanks!

**Comment by mavam** [comment]
I've tweaked the commit message in master slightly so that it's a bit more succinct and descriptive. Thanks for bearing with the nitpickery. :wink:

**Pull request merged**
