### PR TITLE
Change Gamma plot

### PR DESCRIPTION
**Pull request by faridcher**

### CODE REVIEW

**Comment by mavam** [comment]
Thanks for the patch. It looks like there are two issues here: the table with continuous distributions lists the Gamma distribution with a *scale* parameter, but the plot shows the version with shape and *rate* parameterization.

In c0a6fe5f0d59698b7e7aeb734a6d6c96539c6a3b I've adjusted the plots for Exponential and Gamma distribution to be based on the rate parameter. However, I realize there exists an inconsistency now: the Exponential uses beta as rate parameter, whereas the Gamma uses beta as scale parameter.

So instead of fixing the Gamma plot, how about switching the distribution functions so that beta means what people expect.

**Comment by faridcher** [comment]
Matthias, you are right.
First I tried to change the distribution function of Gamma as you stated. However in the Wasserman's book  it says `The exponential distribution is just a Gamma(1, β) distribution`. So replacing beta by 1/beta for the Gamma pdf in the cookbook will violate this quote. furthermore if you check page 53 of the Wasserman's book (Expectation and Variance of Important Random Variables), you will notice the means and variances of that table is consistent with your table of continuous probabilities.
I double checked the wiki page of Gamma distribution and noticed this quote: `If X ~ Exp(λ) then X ~ Gamma(1, 1/λ) (in (k, θ) parametrization) or Gamma(1, λ) (in (α, β) parametrization).` Now I infer that Wasserman's book has this mistake which is not included in the errata as well. I will contact him. 

So yes ,feel free to replace beta by 1/beta in the Gamma pdf,cdf,mean etc as I was trying to do in the first place!

**Comment by mavam** [comment]
This is interesting. I went into the literature and tried to compare various expressions of the Gamma distribution. Here's what I found:

## Wikipedia

wikipedia

## Pitman - Probability

pitman

## Hoel - Introduction into Probability Theory

hoel - introduction to probability theory

## DeGroot - Probability and Statistics

degroot - probability and statistics

## Wasserman - All of Statistics

wassermann - all of statistics

**Comment by mavam** [comment]
Wikipedia, Pitman, and Hoel use λ/θ parameterization. Both DeGroot and Wasserman use β, but attach different semantics to it! This is unfortunate. (I also looked at the German Wikipedia site, my mother tongue, and that version agrees with the English site.) 

Ideally, we chose the form which is most widely used. Most people (including me) will probably flock to Wikipedia first.

I'm inclined to simply add a footnote that some authors, in particular Wasserman, use β as scale parameter.

**Comment by faridcher** [comment]
I checked a couple of other statistics books (on Bayesian), and they use β as the shape parameter just like wikipedia. So yes, changing the pdf of gamma distribution (+exponential) would be a good idea. Just make sure the plot is in concert with the mean and variance of distribution function.

**Pull request closed without merging**
