### PR TITLE
Minor Fixes

### PR DESCRIPTION
**Pull request by faridcher**

### CODE REVIEW

**Comment by mavam** [comment]
Thanks for the PR! Would you mind rebasing it to master and remove the unnecessary merge commits?

**Comment by faridcher** [comment]
The verbose mode ruins the whole distribution table:
snapshot
I think the compressed version is declarative enough to infer the rest of matrix. However it's at your discretion to choose between any version.

```
\left( {\begin{array}{*{20}{c}}
{n{p_1}(1 - {p_1})}&{ - n{p_1}{p_2}}& \cdots \\
{ - n{p_2}{p_1}}&{n{p_2}(1 - {p_2})}& \cdots \\
\begin{array}{l}
 \vdots \\
 - n{p_k}{p_1}
\end{array}&\begin{array}{l}
 \vdots \\
 - n{p_k}{p_2}
\end{array}&\begin{array}{l}
 \vdots \\
 \cdots 
\end{array}
\end{array}\begin{array}{*{20}{c}}
{ - n{p_1}{p_k}}\\
{ - n{p_2}{p_k}}\\
\begin{array}{l}
 \vdots \\
n{p_n}(1 - {p_n})
\end{array}
\end{array}} \right)
```

**Comment by mavam** [comment]
> The verbose mode ruins the whole distribution table:

I see that now, thanks for giving it a shot. I'll use the first version you proposed.

**Comment by mavam** [comment]
I've merged all of your commits and made a few minor tweaks to the commit message, to keep it consistent with the existing one. Thanks again for contributing, you rock!

**Pull request closed without merging**
